powerplay/powerplay/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
from django.views.generic import TemplateView

from app import views, views_guestbook, views_demos

urlpatterns = [
    path('', lambda request: redirect("home")),
    path('home/', TemplateView.as_view(template_name='home.html'), name="home"),

    path('about_gb', TemplateView.as_view(template_name='partials/systems_gb.html'), name="about_gb"),
    path('about_gbp', TemplateView.as_view(template_name='partials/systems_gbp.html'), name="about_gbp"),
    path('about_gbc', TemplateView.as_view(template_name='partials/systems_gbc.html'), name="about_gbc"),

    path('game/', views.game_list, name="game_list"),
    path('game/detail/<slug:slug>/', views.game_detail, name="game_detail"),
    path('game/edit/<slug:slug>/', views.game_edit, name="game_edit"),

    path('game/edit/title/<slug:slug>/', views.edit_title, name="edit_title"),

    path('guestbook/', views_guestbook.guestbook_list, name="guestbook"),
    path('guestbook/remove/<uuid:pk>/', views_guestbook.guestbook_remove_entry, name="guestbook_remove_entry"),
    path('guestbook/stream/', views_guestbook.guestbook_stream, name="guestbook_stream"),

    # Demo Pages
    path('add_stylesheet/', TemplateView.as_view(template_name='samples/add_stylesheet.html'), name="add_stylesheet"),
    path('game/slow/', views_demos.game_list_slow, name="game_list_slow"),

    path('infinite_scroller/', TemplateView.as_view(template_name='infinite_scroller.html'), name="infinite_scroller"),
    path('scroll_frame/<int:page>', views_demos.scroll_frame, name="scroll_frame"),

    path('sse_test', TemplateView.as_view(template_name='sse_demo.html'), name="sse_demo"),
    path('sse', views_demos.sse, name="sse"),

    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
]

powerplay/app/models.py
from django.db import models


class System(models.TextChoices):
    GAMEBOY = "GB"
    GAMEBOY_COLOR = "GBC"


class Game(models.Model):
    title = models.CharField(max_length=255)
    slug = models.CharField(max_length=255)
    music_file = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    publisher = models.CharField(max_length=255)
    studio = models.CharField(max_length=255)
    genre = models.CharField(max_length=255)
    review_score = models.PositiveSmallIntegerField()
    release_date = models.DateField()
    box_art_url = models.URLField()
    box_art = models.BinaryField()
    system = models.CharField(
        max_length=3,
        choices=System.choices,
        default=System.GAMEBOY,
    )


class Screenshot(models.Model):
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    url = models.CharField(max_length=255)
    image = models.BinaryField()

powerplay/app/forms.py
from django import forms
from app.models import Game
from django.core.exceptions import ValidationError


class GameEditForm(forms.ModelForm):
    class Meta:
        model = Game
        fields = ('title', 'description', 'publisher', 'studio', 'genre', 'review_score', 'music_file', 'system')  # fmt: skip

    def clean_publisher(self):
        data = self.cleaned_data["publisher"]
        if data.startswith("123"):
            raise ValidationError("Publisher must not start with '123'")

        return data


class GameEditTitleForm(forms.ModelForm):
    class Meta:
        model = Game
        fields = ("title",)

    def clean_title(self):
        data = self.cleaned_data["title"]
        if data.startswith("123"):
            raise ValidationError("title must not start with '123'")

        return data


class GuestbookForm(forms.Form):

    uuid = forms.CharField(widget=forms.HiddenInput)
    name = forms.CharField(required=True)
    comment = forms.CharField(
        widget=forms.Textarea(
            attrs={
                # "onKeyUp": "checkLength()"
                "data-charlimit-target": "commentField",
                "data-action": "input->charlimit#check",
            }
        )
    )

powerplay/app/views.py
from django.contrib import messages
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, get_object_or_404

from app.models import Game
from app.forms import GameEditForm, GameEditTitleForm

import time


def home(request):
    return render("")


def game_list_slow(request):
    time.sleep(3)
    p = Paginator(Game.objects.all(), 7)
    page = p.page(1)
    return render(request, "game_list.html", {"page": page})


def game_list(request):
    games = Game.objects.all().order_by("-review_score")
    if query := request.GET.get("q"):
        games = games.filter(title__icontains=query)
    p = Paginator(games, 5)
    page = p.page(request.GET.get("page", 1))
    return render(request, "game_list.html", {"page": page})


def game_detail(request, slug):
    game = get_object_or_404(Game, slug=slug)
    return render(request, "game_detail.html", {"game": game})


def game_edit(request, slug):
    game = get_object_or_404(Game, slug=slug)
    if request.method == "POST":
        form = GameEditForm(request.POST, instance=game)
        if form.is_valid():
            form.save()
            messages.success(request, "Your changes have been saved.")
            return redirect("game_detail", slug)
    else:
        form = GameEditForm(instance=game)

    return render(
        request, "game_edit.html", {"form": form} #, status=422 if form.errors else 200
    )


def edit_title(request, slug):
    game = get_object_or_404(Game, slug=slug)
    if request.method == "POST":
        form = GameEditTitleForm(request.POST, instance=game)
        if form.is_valid():
            form.save()
            return render(request, "partials/edit_title.html", {"game": game})
    else:
        form = GameEditTitleForm(instance=game)

    return render(request, "partials/edit_title.html", {"form": form})

powerplay/app/templates/base.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>{% block title %}PowerPlay{% endblock title %}</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/base.css" %}">

    <script src="https://cdn.jsdelivr.net/npm/@hotwired/turbo@8.0.12/dist/turbo.es2017-umd.min.js"></script>
    <script type="module" src="{% static "js/active_tab.js" %}"></script>
    <script type="module" src="{% static "js/musicplayer.js" %}"></script>
    <script type="module" src="{% static "js/bridgeform.js" %}"></script>

    <meta name="turbo-refresh-method" content="morph">

    {% block style %}
    {% endblock style %}

  <body>
    {% include "partials/music_player.html" %}
    <div class="wrapper">

  <div class="container-fluid header-color">

    <div class="container">
    <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-1 d-none d-sm-flex">
      <a href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-decoration-none logo"></a>

      <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
        <li><a data-turbo-action="replace" href="{% url "home" %}" class="nav-link px-2 link-dark">Home</a></li>
        <li><a data-turbo-action="replace" href="{% url "game_list" %}" class="nav-link px-2 link-dark">Game List</a></li>
        <li><a data-turbo-action="replace" href="{% url "guestbook" %}" class="nav-link px-2 link-dark">Guestbook</a></li>

          <form class="mb-0" action="{% url "game_list" %}" method="GET">
          <div class="input-group search-box">
              <input {# data-turbo-permanent id="searchBox" #} name="q" type="text" class="form-control" placeholder="Search">
              <button class="btn btn-primary" type="submit" id="button-addon2">
                <img class="search-icon" src="{% static "img/search.png" %}">
              </button>
          </div>
          </form>
      </ul>

    </header>
    </div>
  </div>


    <!-- Begin page content -->
    <main role="main" class="container mt-3">

      {# MESSAGES #}
      {% if messages %}
      <div class='row'>
          <div class='col-md-12'>
              {% for message in messages %}
              <div class="alert alert-dismissible alert-{% if message.tags == 'error' %}danger{% else %}{{message.tags}}{% endif %}">
                  {{message}}
                  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>
              {% endfor %}
          </div>
      </div>
      {% endif %}

      {% block main %}
      {% endblock main %}
    </main>

    <footer class="footer">
      <div class="container">

      <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
        <li><a href="{% url "game_list_slow" %}" class="nav-link px-2 link-dark">Game List Slow</a></li>
        <li><a href="{% url "infinite_scroller" %}" class="nav-link px-2 link-dark">Infinite Scroller</a></li>
        <li><a href="{% url "add_stylesheet" %}" class="nav-link px-2 link-dark">Add Stylesheet</a></li>
        <li><a href="{% url "sse_demo" %}" class="nav-link px-2 link-dark">Server-Side Events</a></li>
      </ul>

      </div>
    </footer>

  </div>
  <div class="sticky-footer d-sm-none">
    <a data-turbo-action="replace" href="{% url "home" %}" class="sticky-footer__item">
      <img src="{% static "img/house-solid.svg" %}">
      Home
    </a>
    <a data-turbo-action="replace" href="{% url "game_list" %}" class="sticky-footer__item">
      <img src="{% static "img/list-solid.svg" %}">
      Game List
    </a>
    <a data-turbo-action="replace" href="{% url "guestbook" %}" class="sticky-footer__item">
      <img src="{% static "img/signature-solid.svg" %}">
      Guestbook
    </a>
  </div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>

{% block script %}
{% endblock script %}

</body></html>

powerplay/app/templates/game_detail.html
{% extends "base.html" %}
{% load demotags static %}

{% block main %}
    {# <h1>{{game.title}}</h1> #}
    {% include "partials/edit_title.html" %}

    <p class="lead">Released: {{game.release_date}}</p>
    <dl>
        <dt>Studio</dt><dd>{{game.studio}}</dd>
        <dt>Publisher</dt><dd>{{game.publisher}}</dd>
    </dl>


    {% if game.music_file %}
        <button class="btn btn-sm btn-info"
            data-controller="playbutton"
            data-action="playbutton#set"
            data-playbutton-title-value="{{game.title|truncatechars:22}}"
            data-playbutton-image-value="data:image/jpg;base64,{{game.box_art|base64}}"
            data-playbutton-file-value="{% static game.music_file %}">
            Play music sample
        </button>
    {% endif %}


    <p class="lead">{{game.description|safe}}</p>
    {% for screen in game.screenshot_set.all  %}
        <img style="width:150px" class="img-thumbnail" src="data:image/jpg;base64,{{screen.image|base64}}"></td>
    {% endfor%}

    <p data-controller="bridgeform">
        <a data-bridgeform-target="submit" data-bridge-title="Edit" class="btn btn-primary" href="{% url 'game_edit' game.slug %}">Edit</a>
    </p>


{% endblock main %}

powerplay/app/templates/game_edit.html
{% extends "base.html" %}
{% load demotags %}

{% block main %}
    <h1>Edit {{form.instance.title}}</h1>
    <form action="." method="POST" data-controller="bridgeform">
        {% csrf_token %}
        {{form.as_p|prettyform}}
        {% if not turbo_native %}
            <a href="javascript:history.back()" class="btn btn-outline-secondary">Back</a>
        {% endif %}
        <input type="submit" class="btn btn-primary" data-bridgeform-target="submit" data-bridge-title="Submit">
    </form>

{% endblock main %}

powerplay/app/templates/game_list.html
{% extends "base.html" %}
{% load demotags static %}

{% block main %}
    <h1>Game List</h1>

    <table class="table table-striped">
        <thead>
            <th></th>
            <th>Title</th>
            <th>Released</th>
            <th class="d-none d-sm-table-cell">Score</th>
            <th class="d-none d-sm-table-cell">Publisher</th>
            <th class="d-none d-sm-table-cell">Studio</th>
        </thead>
    {% for game in page.object_list  %}
        <tr>
            <td style="width:75px"><img  class="img-thumbnail" src="data:image/jpg;base64,{{game.box_art|base64}}"></td>
            <td class="align-middle"><a href="{% url 'game_detail' game.slug %}">{{game.title}}</a></td>
            <td class="align-middle">{{game.release_date}}</td>
            <td class="d-none d-sm-table-cell align-middle">{{game.review_score}}</td>
            <td class="d-none d-sm-table-cell align-middle">{{game.publisher}}</td>
            <td class="d-none d-sm-table-cell align-middle">{{game.studio}}</td>

        </tr>
    {% endfor %}
    </table>

    <ul class="pagination d-flex justify-content-center mt-3">
        <li class="page-item {% if not page.has_previous %}disabled{% endif %}">
            <a class="page-link" data-turbo-action="replace" href="{% if page.has_previous %}?page={{page.previous_page_number}}{% else %}#{% endif %}">&larr; Previous</a>
        </li>

        <li class="page-item">
            <a class="page-link">
                Page {{ page.number }} of {{ page.paginator.num_pages }}
            </a>
        </li>

        <li class="page-item {% if not page.has_next %}disabled{% endif %}">
            <a class="page-link" data-turbo-action="replace" href="{% if page.has_next %}?page={{page.next_page_number}}{% else %}#{% endif %}">Next &rarr;</a>
        </li>
    </ul>

{% endblock main %}

powerplay/app/templates/guestbook.html
{% extends "base.html" %}
{% load demotags static %}

{% block script %}
<script>
// document.addEventListener('turbo:load', function () {
//     Turbo.connectStreamSource(new EventSource("{% url "guestbook_stream" %}"));
// }, false);
</script>

{# <script type="module" src="{% static "js/charlimit.js" %}"></script> #}
<script>
const MAX_LENGTH=20;
function checkLength(){
  const commentField = document.getElementById("id_comment");
  const charsDiv = document.getElementById("remaining_chars");
  if(commentField.value.length >= MAX_LENGTH){
    commentField.value = commentField.value.substring(0, MAX_LENGTH)
  }
  charsDiv.innerHTML = `${commentField.value.length}/${MAX_LENGTH} chars`
}
</script>

{% endblock script %}

{% block main %}

    <h1>Guestbook</h1>
    <h4>Sign Here</h4>
    <form action="." method="POST">
        {% csrf_token %}
        {{form.as_p|prettyform}}
        <div class="float-end" data-charlimit-target="remainingChars" id="remaining_chars"></div>
        <input type="submit" value="Submit" class="btn btn-primary" data-bridgeform-target="submit" data-bridge-title="Submit">
    </form>

    {# {% include "partials/guestbook_frame.html" %} #}

    <h4>
        Previous Visitors
        {# <span class="badge bg-success" id="counter">{% include "streams/guestbook_entry_counter.html"%}</span> #}
    </h4>

    <div id="guestlist">
    {% for guest in guestlist  %}
        <div id="guestbook-{{guest.uuid}}">
            <b>{{guest.name}}</b> {% if guest.comment %}: {{guest.comment}}{% endif %}
        </div>
        {# {% include "streams/guestbook_entry.html" with entry=guest %} #}
    {% empty %}
        <h5>End of List</h5>
    {% endfor %}
    </div>

{% endblock main %}

powerplay/app/templates/home.html
{% extends "base.html" %}

{% block main %}
    <h1>Home</h1>
    <p class="lead">Welcome to PowerPlay: the ultimate guide to the exquisitly engineered, best-selling 8-bit system in the world.</p>
    <h3>Systems</h3>
    <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item" role="presentation">
        <button class="nav-link active" id="gb-tab" data-bs-toggle="tab" data-bs-target="#gb" type="button" role="tab" aria-controls="gb" aria-selected="true">The Original</button>
        </li>
        <li class="nav-item" role="presentation">
        <button class="nav-link" id="gbp-tab" data-bs-toggle="tab" data-bs-target="#gbp" type="button" role="tab" aria-controls="gbp" aria-selected="false">Gameboy Pocket</button>
        </li>
        <li class="nav-item" role="presentation">
        <button class="nav-link" id="gbc-tab" data-bs-toggle="tab" data-bs-target="#gbc" type="button" role="tab" aria-controls="gbc" aria-selected="false">Gameboy Color</button>
        </li>
    </ul>
    <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="gb" role="tabpanel" aria-labelledby="gb-tab">
            {# {% include "partials/systems_gb.html" %} #}
            <turbo-frame id="system_gb" loading="lazy" src="{% url "about_gb" %}">Loading...</turbo-frame>
        </div>
        <div class="tab-pane fade" id="gbp" role="tabpanel" aria-labelledby="gbp-tab">
            {# {% include "partials/systems_gbp.html" %} #}
            <turbo-frame id="system_gbp" loading="lazy" src="{% url "about_gbp" %}">Loading...</turbo-frame>
        </div>
        <div class="tab-pane fade" id="gbc" role="tabpanel" aria-labelledby="gbc-tab">
            {# {% include "partials/systems_gbc.html" %} #}
            <turbo-frame id="system_gbc" loading="lazy" src="{% url "about_gbc" %}">Loading...</turbo-frame>
        </div>
    </div>

{% endblock main %}

powerplay/app/templates/infinite_scroller.html
{% extends "base.html" %}

{% block main %}
    <h1>Infinite Scroller</h1>

    <turbo-frame id="scroll_frame_1" src="{% url "scroll_frame" 1 %}">

{% endblock main %}

powerplay/app/templates/partials/edit_title.html
{% load demotags %}

<turbo-frame id="edit-title">
{% if form %}
    <form method="POST" action="{{request.META.PATH_INFO}}">
        {% csrf_token %}
        {{form.as_p|prettyform}}
        <input type="submit" class="btn btn-primary">
    </form>
{% else %}
    <h1>{{game.title}} - <a href="{% url 'edit_title' game.slug %}">Edit</a></h1>
{% endif %}
</turbo-frame>

powerplay/app/templates/partials/guestbook_frame.html
<turbo-frame id="guestbook_frame">
    <div style="border:2px green dotted">
    <h4>
        Previous Visitors
        <span class="badge bg-success">{{guest_count}}</span>
    </h4>

    {% for guest in guestlist  %}
        <div>
            <b>{{guest.name}}</b> {% if guest.comment %}: {{guest.comment}}{% endif %}
        </div>
    {% empty %}
        <h5>End of List</h5>
    {% endfor %}
    </div>
</turbo-frame>

powerplay/app/templates/partials/infinite_scroll.html
<turbo-frame id="scroller_{{page.number}}">
{% for object in page.object_list %}
    <div>{{object}}</div>
{% endfor %}

{% comment %}
{% if page.has_next %}
<turbo-frame
    id="scroller_{{page.next_page_number}}"
    src="{% url "infinite_scroll" page.next_page_number %}"
    loading="lazy">
  Loading next page...
</turbo-frame>
{% endif %}
{% endcomment %}

</turbo-frame>

powerplay/app/templates/partials/music_player.html
{% load static %}

<div id="musicplayer_id" {# data-turbo-permanent #} class="mejs_container text-white bg-dark bg-gradient p-2 d-none" data-controller="musicplayer">
  <div class="d-flex gap-3">
    <img src="{% static "img/gb.jpg" %}" alt="" data-musicplayer-target="image">
    <div class="d-flex flex-column">
      <div class="d-flex">
        <h4 class="flex-grow-1 text-truncate" data-musicplayer-target="title">Song title</h4>
        <a class="float-end" style="cursor:pointer" data-action="musicplayer#hide">[Close]</a>
      </div>
      <audio controls width="100%" data-musicplayer-target="audio">
        <source src="">
        Your browser does not support the audio tag.
      </audio>
    </div>
  </div>
</div>

powerplay/app/templates/partials/scroll_frame.html
<turbo-frame id="scroll_frame_{{page.number}}">
{% for object in page.object_list %}
    <div>{{object}}</div>
{% endfor %}

{% comment %}
{% if page.has_next %}
<turbo-frame
    id="scroll_frame_{{page.next_page_number}}"
    src="{% url "scroll_frame" page.next_page_number %}"
    loading="lazy">
  Loading next page...
</turbo-frame>
{% endif %}
{% endcomment %}

</turbo-frame>

powerplay/app/templates/partials/systems_gb.html
{% load static %}
{# <turbo-frame id="system_gb"> #}
<h2 class="mt-3">The Original Gameboy</h2>
<img src="{% static "img/gb.jpg" %}" class="float-end">
The Game Boy is an 8-bit fourth generation handheld game console developed and manufactured by Nintendo. It was first released in Japan on April 21, 1989, in North America later the same year, and in Europe in late 1990. It was designed by the same team that developed the Game & Watch series of handheld electronic games and several Nintendo Entertainment System (NES) games: Satoru Okada, Gunpei Yokoi, and Nintendo Research & Development 1.
{# </turbo-frame> #}

powerplay/app/templates/partials/systems_gbc.html
{% load static %}
{# <turbo-frame id="system_gbc"> #}
<h2 class="mt-3">Gameboy Color</h2>
<img src="{% static "img/gbc.jpg" %}" class="float-end">
<p>The Game Boy Color (commonly abbreviated as GBC) is an 8-bit handheld game console, manufactured by Nintendo, which was released in Japan on October 21, 1998 and to international markets that November. It is the successor to the Game Boy and is part of its product line. Critics like IGN consider it more akin to a hardware revision than a next generation product.</p>

<p>The handheld features a color screen rather than monochrome, but it is not backlit. It is slightly thicker and taller and features a slightly smaller screen than Game Boy Pocket, its immediate predecessor. As with the original Game Boy, it has a custom 8-bit processor made by Sharp that is considered a hybrid between the Intel 8080 and the Zilog Z80. The American English spelling of the system's name, Game Boy Color, remains consistent throughout the world.</p>

<p>The GBC is part of the fifth generation of video game consoles. The Game Boy and the Game Boy Color combined have sold 118.69 million units worldwide making them the fourth best-selling system of all time. Its best-selling games are Pokémon Gold and Silver, which shipped 23 million units worldwide.</p>
{# </turbo-frame> #}

powerplay/app/templates/partials/systems_gbp.html
{% load static %}
{# <turbo-frame id="system_gbp"> #}
<h2 class="mt-3">Gameboy Pocket</h2>
<img style="width:200px" src="{% static "img/gbp.jpg" %}" class="float-end">
<p>The Game Boy Pocket is the first redesigned version of the original Game Boy. Released in 1996, it has the features of its predecessor, but in a smaller and lighter form factor.</p>

<p>Another notable improvement over the original Game Boy is its true black-and-white display with reduced sprite blurring, rather than the "pea soup" monochromatic display of the original Game Boy. The Game Boy Pocket takes two AAA batteries versus the original's four AA batteries for roughly ten hours of gameplay. The Game Boy Pocket initially omitted the LED indicating battery levels, but it was added to later units in response to public demand.</p>
{# </turbo-frame> #}

powerplay/app/templates/samples/add_stylesheet.html
{% extends "base.html" %}
{% load static %}

{% block style %}
    {% comment %}
        Web browsers do not remove stylesheets or
        Use `data-turbo-track="reload"` to force a reload when stylesheet/script or added or removed
    {% endcomment %}
    <link rel="stylesheet" href="{% static "css/blue_body.css" %}" {# data-turbo-track="reload" #}>
{% endblock style %}

{% block main %}
    <h1>Add Stylesheet</h1>
    <p class="lead">New stylesheet has been added.</p>

    [<a href="{% url 'home' %}">Go Home with Turbo</a>]
    [<a data-turbo="false" href="{% url 'home' %}">Go Home without Turbo</a>]

{% endblock main %}

powerplay/app/templates/sse_demo.html
{% extends "base.html" %}

{% block script %}
<script>
document.addEventListener("turbo:load", function() {
    if (window["EventSource"] && window["Turbo"]) {
        Turbo.connectStreamSource(new EventSource("/sse"));
    } else {
        console.warn("Turbo Streams over SSE not available");
    }
});
</script>
{% endblock script %}

{% block main %}
    <h1>Server Side Events</h1>

    <div id="messages">
        <h1>Messages</h1>
    </div>

{% endblock main %}

powerplay/app/templates/streams/guestbook_entry.html
<turbo-stream action="prepend" target="guestlist">
  <template>
    <div id="guestbook-{{entry.uuid}}">
        <b>{{entry.name}}</b> {% if entry.comment %}: {{entry.comment}}{% endif %}
        {# [<a href="{% url 'guestbook_remove_entry' entry.uuid %}">Remove</a>] #}
    </div>
  </template>
</turbo-stream>

powerplay/app/templates/streams/guestbook_entry_counter.html
<turbo-stream action="update" targets="#counter">
  <template>
    {{guest_count}}
  </template>
</turbo-stream>

powerplay/app/templates/streams/guestbook_entry_remove.html
<turbo-stream action="remove" target="guestbook-{{uuid}}"></turbo-stream>